### ISSUE TITLE
Malformed geometries

### ISSUE THREAD

**Issue by Amoki** [xeokit/xeokit-gltf-to-xkt#11]
Some geometries are malformed:
![Screenshot from 2020-01-13 14-43-07](https://user-images.githubusercontent.com/1349751/72260805-e7d50f80-3613-11ea-81e6-72b71f68199d.png)

And when I load the original glTF:
![Screenshot from 2020-01-13 14-44-23](https://user-images.githubusercontent.com/1349751/72260692-af353600-3613-11ea-8182-00ffbf7ca01c.png)

Some pipes are squared and the pump is the grandchild of Picasso.
The UUID of the pump is `20QHfHp2vAohZ2X9d2i1pR` is you want to find it easily.

Do you have any idea?
@xeolabs @tmarti
[buggy.zip](https://github.com/xeokit/xeokit-gltf-to-xkt/files/4053855/buggy.zip)

**Comment by xeolabs** [comment]
Looks like a geometry quantization accuracy error, ie. loss of precision converting from floats to integers, possibly.

I'll take a look at this one this week or next. Possibly the solution is to extend gltf2xkt to scale the model so that the floating point value ranges of the positions can quantize to the value ranges of the quantized integers with less loss of precision. That was something @tmarti and I were discussing last year - seems a good idea to go with that soon.

**Comment by xeolabs** [comment]
@Amoki can I get the original IFC model?

I found that the glTF model loads fine into xeokit, as you found, with geometry compression not losing accuracy.

However the ````xeokit-gltf-to-xkt```` tool seems to be losing accuracy. So that's what I'll debug.

I suspect that the problem is with the non-instanced geometries,  which are being quantized/dequantized as a unit, using the same quzntization/dequantization matrix, derived from the their collective boundary.

Long-term, I'll extend XKT format to do that part better, or to have a "don't compress" mode, which will make the file ~20% bigger, with ~20-25% larger memory footprint. 

Short-term, I'd like to play around with the pipeline, specifically to use ````IfcConvert's``` (undocumented) ````--center-model```` option, which will center the model at ````[0,0,0]````, and may very likely compensate for this loss of accuracy.

So, the original IFC would be handy - you could email that directly, if acceptable.

**Comment by Amoki** [comment]
The `--center-model` option conflict with multi-models when models are not aligned. For example, if we have 2 buildings side by side in 2 IFC models, the `--center-model` option may output each building in [0,0,0] and we won't be able to open them both in the viewer.

Our workaround implies higher coordinates (up to a few hundreds/thousands) which implies this issue. 

The AABB of the model is not huge ([ 5.898022174835205, -3.6000001430511475, -1320.6759338378906, 38.67945861816406, 24.58912467956543, -1283.0242614746094 ]) but a bit far. Could the xkt convert do a `--center` itself during quantization and set the model to the right place at loading time? Or something like that?

**Comment by xeolabs** [comment]
> Could the xkt convert do a --center itself during quantization and set the model to the right place at loading time? Or something like that?

Yes, after some experimentation, that seems to be the best approach. I'm working on V3 of the XKT format, which will do exactly that. The model will be centered, and XKT will include the original origin of the model, for xeokit to translate the model back to while loading/rendering.

Though having that IFC model would be a useful resource for developing XKT V3, if you're able to share it.

**Comment by xeolabs** [comment]
The issue was that both batched and instanced geometries were using the same geometry dequantization matrix. 

The dequantization matrix is generated from the extents of all geometries in the model. 

As ````xeokit-gltf-to-xkt```` parses glTF, it determines batched geometries to be those geometries that are used only once, each by a single object, while instanced geometries are those that are reused by multiple objects.

The tool immediately transforms the batched geometry's positions by their object's transforms, effectively baking those transforms into the batched geometry's positions.

For each instanced geometry, the tool leaves its positions untransformed, and saved the transform on the objects that instance it. Instanced geometries are typically centered at the ````[0,0,0]```` origin.

From both batched and instanced geometries, the tool computes the same bounding box, then computes the dequantization matrix, for all geometries, from that boundary.

The problem arises when the model is translated far away from the origin. In the case, we get a boundary that is stretched between the instanced geometries, centered at the origin, and the transformed, batched geometries. The boundary can then become too large for the derived dequantization matrix to accurately decode all the geometry positions (both instanced and batched).

The solution is to have a separate dequantization matrix for instanced geometries.

This solution is implemented in bothh ````xeokit-gltf-to-xkt```` and ````XKTLoaderPlugin```` by extending the ````XKT```` format to V3, to include that extra dequantization matrix for instanced geometries.

````XKTLoaderPlugin```` will still support ````XKT```` V1 and V2.

**Comment by Amoki** [comment]
Nice! Well done and thank you very much!
